[advisories]
ignore = [
  "RUSTSEC-2021-0041", # parse_duration DoS with too-large exponent
  "RUSTSEC-2020-0056", # stdweb crate is unmaintained (transitive thru time 0.2)
  "RUSTSEC-2024-0384", # rhai only uses instant for wasm, which we don't use
]

[licenses]
confidence-threshold = 0.65  # ring's license can't be recognized well
allow = [
  "MPL-2.0",
  "MIT",
  "ISC",
  "Unicode-3.0",
  "CC0-1.0",
  "Apache-2.0",
  "BSD-3-Clause",
  "0BSD"
]
exceptions = [
    {name="ring", allow=["OpenSSL"]}
]

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
highlight = "lowest-version"
allow = [
]
deny = [
]

# Certain crates/versions that will be skipped when doing duplicate detection.
skip = [
]
skip-tree = [
    # This is useful for dev-dependencies like criterion which often pin their own versions of rand
]
